Repository SteffanoP/cata-sucata, pull requests merged in 2023-09, with the labels that each got.

#24 [CS-140] Cadastrar Área de Coleta
  fronteend/src/App.js
  fronteend/src/components/Sidebar.jsx
  fronteend/src/pages/CadastroAreaColeta/index.jsx
Labels: enhancement

#27 [CS-129] Upsert sensor
  backend/functions/upsert-sensor/function.json
  backend/functions/upsert-sensor/main.py
Labels: backend

#28 [CS-127][CS-133] Visualizar área de coleta no mapa e sua disponibilidade
  fronteend/package-lock.json
  fronteend/package.json
  fronteend/src/App.js
  fronteend/src/components/FavoritesContext.jsx
  fronteend/src/components/MenuLateral.jsx
  fronteend/src/components/NewMapArea.jsx
  fronteend/src/components/RightSidebar.jsx
  fronteend/src/pages/CadastroAreaColeta/index.jsx
  fronteend/src/pages/Map/map.jsx
Labels: enhancement, frontend
