Repository SteffanoP/cata-sucata, pull requests merged in 2023-08, with the labels that each got.

#2 [CS-35] Exemplo login azure
  frontend/exemplo-login-azure/.eslintrc.cjs
  frontend/exemplo-login-azure/.gitignore
  frontend/exemplo-login-azure/README.md
  frontend/exemplo-login-azure/index.html
  frontend/exemplo-login-azure/package-lock.json
  frontend/exemplo-login-azure/package.json
  frontend/exemplo-login-azure/public/vite.svg
  frontend/exemplo-login-azure/src/App.css
  frontend/exemplo-login-azure/src/App.jsx
  frontend/exemplo-login-azure/src/assets/react.svg
  frontend/exemplo-login-azure/src/authConfig.js
  frontend/exemplo-login-azure/src/components/PageLayout.jsx
  frontend/exemplo-login-azure/src/components/ProfileData.jsx
  frontend/exemplo-login-azure/src/components/SignInButton.jsx
  frontend/exemplo-login-azure/src/components/SignOutButton.jsx
  frontend/exemplo-login-azure/src/graph.js
  frontend/exemplo-login-azure/src/index.css
  frontend/exemplo-login-azure/src/main.jsx
  frontend/exemplo-login-azure/vite.config.js
Labels: auth

#5 [CS-104] Exibir os Status das Lixeiras
  fronteend/.gitignore
  fronteend/README.md
  fronteend/package-lock.json
  fronteend/package.json
  fronteend/public/favicon.ico
  fronteend/public/index.html
  fronteend/public/logo192.png
  fronteend/public/logo512.png
  fronteend/public/manifest.json
  fronteend/public/robots.txt
  fronteend/src/App.css
  fronteend/src/App.js
  fronteend/src/components/MenuLateral.jsx
  fronteend/src/components/MiniDrawer.jsx
  fronteend/src/components/Navbar.jsx
  fronteend/src/index.css
  fronteend/src/index.js
  fronteend/src/pages/Dashboard/index.jsx
Labels: enhancement, frontend

#12 [CS-125][CS-126] Send Localization and Unique Identification for sensors
  .gitignore
  hardware/nodemcu-esp8266/iot_configs.h
  hardware/nodemcu-esp8266/nodemcu-esp8266.ino
Labels: enhancement, hardware

#14 [CS-107] Visualização Gráfica das Lixeiras em um Mapa
  .github/workflows/deploy-to-production.yml
  backend/functions/getting_started.md
  backend/functions/requirements.txt
  fronteend/package-lock.json
  fronteend/package.json
  fronteend/src/App.js
  fronteend/src/assets/cata-sucata.png
  fronteend/src/assets/trash.png
  fronteend/src/components/MapArea.jsx
  fronteend/src/components/MiniDrawer.jsx
  fronteend/src/components/RightSidebar.jsx
  fronteend/src/components/Sidebar.jsx
  fronteend/src/pages/Map/map.jsx
Labels: enhancement, frontend

#17 Organização e Continuação da Tela Status
  fronteend/package-lock.json
  fronteend/package.json
  fronteend/src/components/Chart.jsx
  fronteend/src/components/MiniDrawer.jsx
  fronteend/src/components/Navbar.jsx
  fronteend/src/pages/Dashboard/index.jsx
Labels: frontend

#19 [CS-131][CS-135] Armazena dados dos sensores no Azure CosmosDB
  .gitignore
  backend/functions/requirements.txt
  backend/functions/shared_code/get_data.py
  backend/functions/shared_code/get_message.py
  backend/functions/status-preview/main.py
  hardware/nodemcu-esp8266/iot_configs.h
  hardware/nodemcu-esp8266/nodemcu-esp8266.ino
Labels: enhancement

#20 [CS-128] Sistema de Notificações do Usuário
  fronteend/package-lock.json
  fronteend/src/App.js
  fronteend/src/components/Navbar.jsx
  fronteend/src/components/NotificationsContext.jsx
  fronteend/src/pages/Dashboard/index.jsx
Labels: enhancement
